/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lenguajesformales1;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.table.DefaultTableModel;
import otros.infoToken;

/**
 *
 * @author alpha
 */
public class RecuentoToken extends javax.swing.JDialog {
    private ArrayList<infoToken> resultados;
    DefaultTableModel ingresarTabla;
    /**
     * Creates new form RecuentoToken
     */
    public RecuentoToken(java.awt.Frame parent, boolean modal, ArrayList<infoToken> resultados) {
        super(parent, modal);
        initComponents();
        ingresarTabla = (DefaultTableModel) TableRecuento.getModel();
        this.resultados=resultados;
        Ordenar();
        BuscarRepeticiones();
        crearTabla();
    }
    
    public void Ordenar(){
        Collections.sort(resultados, new Comparator<infoToken>() {
        public int compare(infoToken obj1, infoToken obj2) {
            return obj1.getToken().compareTo(obj2.getToken());
        }
        });
    }
    
    public void BuscarRepeticiones(){
        String Palabra="";
        for (int i = 0; i < resultados.size(); i++) {
            if (i==0) {
               Palabra=resultados.get(i).getToken();
               resultados.get(i).setRepeticiones(1); 
            }
            if (i>0) {
                if (Palabra.equals(resultados.get(i).getToken())) {
                    resultados.get(i).setRepeticiones(resultados.get(i-1).getRepeticiones()+1);
                    resultados.get(i-1).setRepeticiones(-1);
                }else{
                    Palabra=resultados.get(i).getToken();
                    resultados.get(i).setRepeticiones(1);
                }
            }
        }
    }
    
    public void crearTabla(){
        for (int i = 0; i < resultados.size(); i++) {
            if (resultados.get(i).getRepeticiones()>0) {
                ingresarTabla.addRow(new Object[]{resultados.get(i).getToken(), resultados.get(i).getIdentificador(), resultados.get(i).getRepeticiones()});
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableRecuento = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Recuento de Tokens");

        TableRecuento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lexema", "Nombre Token", "Repeticiones"
            }
        ));
        jScrollPane1.setViewportView(TableRecuento);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(jLabel1)
                .addContainerGap(389, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableRecuento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
